name: Check PR

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  assembleAndroidDebug:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Assemble Android Debug
        run: ./gradlew assembleDebug --stacktrace

  assembleAndroidRelease:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Assemble Android Release
        run: ./gradlew assembleRelease --stacktrace

# UI tests on CI are flaky
#  connectedTests:
#    runs-on: macos-latest
#    needs: [assembleDebug, assembleRelease]
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: 'zulu'
#          java-version: '17'
#
#      - name: Run connected tests
#        uses: ReactiveCircus/android-emulator-runner@v2
#        with:
#          api-level: 33
#          arch: x86_64
#          script: ./gradlew connectedCheck --stacktrace

  test:
    runs-on: macos-latest
    needs: [assembleAndroidDebug, assembleAndroidRelease]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run tests
        run: |
          ./gradlew :jsontree:jvmTest --tests com.sebastianneubauer.jsontree.JsonTreeParserTest --stacktrace
          ./gradlew :jsontree:jvmTest --tests com.sebastianneubauer.jsontree.JsonTreeSearchTest --stacktrace
          ./gradlew :jsontree:jvmTest --tests com.sebastianneubauer.jsontree.SearchStateTest --stacktrace
          ./gradlew :jsontree:jvmTest --tests com.sebastianneubauer.jsontree.ExtensionsTest --stacktrace

  detekt:
    runs-on: macos-latest
    needs: [assembleAndroidDebug, assembleAndroidRelease]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Run detekt
        run: ./gradlew detektAll